from enum import StrEnum


class Role(StrEnum):
    RENTER = "RENTER"
    AGENT = "AGENT"
    LANDLORD = "LANDLORD"
    REVIEWER = "REVIEWER"
    ADMIN = "ADMIN"


LISTER_ROLES = frozenset({Role.AGENT, Role.LANDLORD})
STAFF_ROLES = frozenset({Role.REVIEWER, Role.ADMIN})


class AgentVerificationStatus(StrEnum):
    DRAFT = "DRAFT"
    SUBMITTED = "SUBMITTED"
    IN_REVIEW = "IN_REVIEW"
    VERIFIED = "VERIFIED"
    REJECTED = "REJECTED"
    SUSPENDED = "SUSPENDED"
    EXPIRED = "EXPIRED"


class VerificationStatus(StrEnum):
    """Property verification case status."""

    DRAFT = "DRAFT"
    SUBMITTED = "SUBMITTED"
    IN_REVIEW = "IN_REVIEW"
    INSPECTION_BOOKED = "INSPECTION_BOOKED"
    VERIFIED = "VERIFIED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"


class PropertyVerificationState(StrEnum):
    """Denormalised summary on Property (NOT_SUBMITTED + case statuses)."""

    NOT_SUBMITTED = "NOT_SUBMITTED"
    DRAFT = "DRAFT"
    SUBMITTED = "SUBMITTED"
    IN_REVIEW = "IN_REVIEW"
    INSPECTION_BOOKED = "INSPECTION_BOOKED"
    VERIFIED = "VERIFIED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"


class CheckType(StrEnum):
    AGENT_IDENTITY_SEEN = "AGENT_IDENTITY_SEEN"
    AUTHORITY_TO_MARKET_SEEN = "AUTHORITY_TO_MARKET_SEEN"
    PROPERTY_LOCATION_INSPECTED = "PROPERTY_LOCATION_INSPECTED"
    PHOTOS_MATCH_INSPECTION = "PHOTOS_MATCH_INSPECTION"
    FEE_BREAKDOWN_CONFIRMED = "FEE_BREAKDOWN_CONFIRMED"
    OWNER_CONTACT_CONFIRMED = "OWNER_CONTACT_CONFIRMED"
    LISTING_AVAILABILITY_CONFIRMED = "LISTING_AVAILABILITY_CONFIRMED"
    SUPPORTING_DOCUMENTS_REVIEWED = "SUPPORTING_DOCUMENTS_REVIEWED"


CHECK_LABELS: dict[CheckType, str] = {
    CheckType.AGENT_IDENTITY_SEEN: "Agent identity seen",
    CheckType.AUTHORITY_TO_MARKET_SEEN: "Authority to market the property seen",
    CheckType.PROPERTY_LOCATION_INSPECTED: "Property location inspected",
    CheckType.PHOTOS_MATCH_INSPECTION: "Property photos match inspection",
    CheckType.FEE_BREAKDOWN_CONFIRMED: "Fee breakdown confirmed",
    CheckType.OWNER_CONTACT_CONFIRMED: "Owner or property manager contact confirmed",
    CheckType.LISTING_AVAILABILITY_CONFIRMED: "Listing availability confirmed",
    CheckType.SUPPORTING_DOCUMENTS_REVIEWED: "Supporting documents reviewed",
}

# These must be PASSED (not merely NOT_APPLICABLE) before a property can be VERIFIED.
MANDATORY_CHECKS = frozenset(
    {
        CheckType.AGENT_IDENTITY_SEEN,
        CheckType.AUTHORITY_TO_MARKET_SEEN,
        CheckType.PROPERTY_LOCATION_INSPECTED,
        CheckType.FEE_BREAKDOWN_CONFIRMED,
        CheckType.LISTING_AVAILABILITY_CONFIRMED,
    }
)


class CheckResult(StrEnum):
    NOT_STARTED = "NOT_STARTED"
    PASSED = "PASSED"
    FAILED = "FAILED"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class DocumentReviewStatus(StrEnum):
    UPLOADED = "UPLOADED"
    REVIEWED = "REVIEWED"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"


class DocumentType(StrEnum):
    AUTHORITY_LETTER = "AUTHORITY_LETTER"
    OWNER_ID = "OWNER_ID"
    AGENT_ID = "AGENT_ID"
    TITLE_DOCUMENT_COPY = "TITLE_DOCUMENT_COPY"
    UTILITY_BILL = "UTILITY_BILL"
    TENANCY_AGREEMENT_TEMPLATE = "TENANCY_AGREEMENT_TEMPLATE"
    FEE_SCHEDULE = "FEE_SCHEDULE"
    OTHER = "OTHER"


class MediaType(StrEnum):
    PHOTO = "PHOTO"
    VIDEO_LINK = "VIDEO_LINK"


class PropertyType(StrEnum):
    SELF_CONTAINED = "SELF_CONTAINED"
    MINI_FLAT = "MINI_FLAT"
    FLAT = "FLAT"
    DUPLEX = "DUPLEX"
    TERRACE = "TERRACE"
    BUNGALOW = "BUNGALOW"
    ROOM = "ROOM"
    SHOP = "SHOP"
    OFFICE = "OFFICE"
    LAND = "LAND"


class ServiceType(StrEnum):
    RENTAL = "RENTAL"
    SALES = "SALES"
    COMMERCIAL = "COMMERCIAL"
    PROPERTY_MANAGEMENT = "PROPERTY_MANAGEMENT"
    SHORT_LET = "SHORT_LET"
    RELOCATION_SUPPORT = "RELOCATION_SUPPORT"


class AvailabilityStatus(StrEnum):
    AVAILABLE = "AVAILABLE"
    RESERVED = "RESERVED"
    LET = "LET"
    UNAVAILABLE = "UNAVAILABLE"


class SlotStatus(StrEnum):
    OPEN = "OPEN"
    BOOKED = "BOOKED"
    CANCELLED = "CANCELLED"


class BookingStatus(StrEnum):
    REQUESTED = "REQUESTED"
    CONFIRMED = "CONFIRMED"
    DECLINED = "DECLINED"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


ACTIVE_BOOKING_STATUSES = (BookingStatus.REQUESTED, BookingStatus.CONFIRMED)


class HouseSearchStatus(StrEnum):
    SUBMITTED = "SUBMITTED"
    MATCHING = "MATCHING"
    ASSIGNED = "ASSIGNED"
    CONTACTED = "CONTACTED"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class Purpose(StrEnum):
    RENT = "RENT"
    PURCHASE = "PURCHASE"


class FurnishedPreference(StrEnum):
    FURNISHED = "FURNISHED"
    UNFURNISHED = "UNFURNISHED"
    EITHER = "EITHER"


class EnquiryStatus(StrEnum):
    PENDING = "PENDING"
    RESPONDED = "RESPONDED"
    CLOSED = "CLOSED"


class ReservationStatus(StrEnum):
    PENDING_PAYMENT = "PENDING_PAYMENT"
    PENDING_RELEASE = "PENDING_RELEASE"
    RELEASED = "RELEASED"
    REFUNDED = "REFUNDED"
    CANCELLED = "CANCELLED"


class ReportReason(StrEnum):
    FAKE_IDENTITY = "FAKE_IDENTITY"
    FALSE_PROPERTY_INFORMATION = "FALSE_PROPERTY_INFORMATION"
    MISLEADING_PHOTOS = "MISLEADING_PHOTOS"
    UNEXPECTED_FEES = "UNEXPECTED_FEES"
    PROPERTY_UNAVAILABLE_AFTER_PAYMENT = "PROPERTY_UNAVAILABLE_AFTER_PAYMENT"
    HARASSMENT = "HARASSMENT"
    PAYMENT_PRESSURE = "PAYMENT_PRESSURE"
    FRAUD_SUSPICION = "FRAUD_SUSPICION"
    UNAUTHORIZED_AGENT_ACTIVITY = "UNAUTHORIZED_AGENT_ACTIVITY"


class ReportStatus(StrEnum):
    OPEN = "OPEN"
    IN_REVIEW = "IN_REVIEW"
    RESOLVED = "RESOLVED"
    REJECTED = "REJECTED"


class PlaceCategory(StrEnum):
    MARKET = "MARKET"
    RESTAURANT = "RESTAURANT"
    CHURCH = "CHURCH"
    CLUB = "CLUB"


class PlaceReportReason(StrEnum):
    WRONG_LOCATION = "WRONG_LOCATION"
    PERMANENTLY_CLOSED = "PERMANENTLY_CLOSED"
    WRONG_OPENING_HOURS = "WRONG_OPENING_HOURS"
    WRONG_PHONE_NUMBER = "WRONG_PHONE_NUMBER"
    WRONG_NAME_OR_CATEGORY = "WRONG_NAME_OR_CATEGORY"
    DUPLICATE = "DUPLICATE"
    OTHER = "OTHER"


class PlaceReportStatus(StrEnum):
    OPEN = "OPEN"
    RESOLVED = "RESOLVED"
    REJECTED = "REJECTED"
